#!/usr/bin/env bash

git config --global user.email "${GIT_USER_EMAIL}"
git config --global user.name "${GIT_USER_NAME}"
git config --global init.defaultBranch "main"
git config --global core.editor "nvim -f"
git config --global push.autoSetupRemote true
