#!/usr/bin/env bash

version="release-0.11"
if [ ! -z $NVIM_VERSION ]; then
    version="$NVIM_VERSION"
fi

echo "version: \"$version\""

# neovim btw
if [ ! -d $HOME/neovim ]; then
    git clone https://github.com/neovim/neovim.git $HOME/neovim
fi

sudo pacman -S --noconfirm base-devel cmake unzip ninja gettext git

# Clean any existing build
if [ -d ~/neovim ]; then
    make -C ~/neovim distclean 2>/dev/null || true
    rm -rf ~/neovim/.deps 2>/dev/null || true
fi

git -C ~/neovim fetch --all
git -C ~/neovim checkout $version

# Update package database to fix mirror issues
sudo pacman -Syy

make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/neovim install

git clone https://github.com/ThePrimeagen/harpoon.git $HOME/harpoon
cd $HOME/harpoon
git fetch
git checkout harpoon2

sudo pacman -S --noconfirm luarocks

sudo luarocks install luacheck

# Install other tools (but NOT neovim package to avoid overwriting our build)
sudo pacman -S --noconfirm --needed gcc make git ripgrep fd unzip

git clone https://github.com/Logan-Ruf/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
