#!/usr/bin/env bash

version="v0.10.2"
if [ ! -z $NVIM_VERSION ]; then
    version="$NVIM_VERSION"
fi

echo "version: \"$version\""

# neovim btw
if [ ! -d $HOME/neovim ]; then
    git clone https://github.com/neovim/neovim.git $HOME/neovim
fi

sudo pacman -S --noconfirm base-devel cmake unzip ninja gettext git

sudo pacman -S --noconfirm lua lua51 

git -C ~/neovim fetch --all
git -C ~/neovim checkout $version

make -C ~/neovim clean
make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/neovim install

git clone https://github.com/ThePrimeagen/harpoon.git $HOME/harpoon
cd $HOME/harpoon
git fetch
git checkout harpoon2

sudo pacman -S --noconfirm luarocks

sudo luarocks install luacheck

# Kickstart NeoVIM
sudo pacman -S --noconfirm --needed gcc make git ripgrep fd unzip neovim

git clone https://github.com/Logan-Ruf/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
