#!/usr/bin/env bash
sudo pacman -Syy --noconfirm tmux

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tmux-sensible.git ~/.tmux/plugins/tpm
git clone https://github.com/fabioluciano/tmux-tokyo-night.git ~/.tmux/plugins/tpm

